In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
df = pd.read_csv("data/DataSet.csv")
df.drop(columns=["Unnamed: 0"], inplace=True)

In [33]:
df.head()

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,...,F3915,F3916,F3917,F3918,F3919,F3920,F3921,F3922,F3923,F3924
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,1,0,0,1,0,0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,1,0,1,0,0,0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,1,0,0,1,0,0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,1,0,0,1,0,0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,1,0,1,0,0,0

In [34]:
df.columns

Index(['F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10',
       ...
       'F3915', 'F3916', 'F3917', 'F3918', 'F3919', 'F3920', 'F3921', 'F3922',
       'F3923', 'F3924'],
      dtype='str', length=3924)

In [35]:
df.shape

(9082, 3924)

In [36]:
df.isnull().sum()

F1       6491
F2       7550
F3       7634
F4       6491
F5       7550
         ...
F3920       0
F3921       0
F3922       0
F3923       0
F3924       0
Length: 3924, dtype: int64

In [37]:
Fullnullcolumns = df.columns[df.isnull().all()]

In [38]:
Fullnullcolumns.shape[0]

63

In [39]:
print(Fullnullcolumns)

Index(['F128', 'F131', 'F182', 'F185', 'F189', 'F192', 'F236', 'F239', 'F290',
       'F293', 'F390', 'F393', 'F437', 'F440', 'F492', 'F495', 'F539', 'F542',
       'F594', 'F597', 'F2312', 'F2360', 'F2455', 'F2458', 'F2552', 'F2555',
       'F2607', 'F2655', 'F2707', 'F2753', 'F2756', 'F2807', 'F2810', 'F2814',
       'F2860', 'F2863', 'F2914', 'F2917', 'F2921', 'F2924', 'F2968', 'F2971',
       'F3027', 'F3030', 'F3074', 'F3077', 'F3133', 'F3179', 'F3182', 'F3233',
       'F3236', 'F3341', 'F3344', 'F3449', 'F3452', 'F3503', 'F3506', 'F3557',
       'F3560', 'F3665', 'F3668', 'F3773', 'F3776'],
      dtype='str')

In [40]:
df.drop(columns=Fullnullcolumns, inplace=True)

In [41]:
df.head()

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,...,F3915,F3916,F3917,F3918,F3919,F3920,F3921,F3922,F3923,F3924
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,1,0,0,1,0,0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,1,0,1,0,0,0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,1,0,0,1,0,0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,1,0,0,1,0,0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,1,0,1,0,0,0

In [42]:
df.isnull().sum()

F1       6491
F2       7550
F3       7634
F4       6491
F5       7550
         ...
F3920       0
F3921       0
F3922       0
F3923       0
F3924       0
Length: 3861, dtype: int64

In [43]:
df.describe()

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,...,F3915,F3916,F3917,F3918,F3919,F3920,F3921,F3922,F3923,F3924
count,2591.000000,1532.000000,1448.000000,2591.000000,1532.000000,1448.000000,855.000000,488.000000,725.000000,855.000000,...,9082.000000,9082.000000,9082.000000,9082.000000,9082.000000,9082.000000,9082.000000,9082.000000,9082.000000,9082.000000
mean,0.679722,0.656129,0.724731,0.691721,0.659497,0.727811,0.487135,0.441844,0.508676,0.487275,...,0.002532,0.780335,0.213719,0.020921,1.280775,0.210636,0.336930,0.562431,0.066505,0.008919
std,0.392573,0.398420,0.408869,0.401105,0.404242,0.413717,0.399929,0.435882,0.398278,0.423618,...,0.050263,0.414043,0.409954,0.143126,1.008499,0.569385,0.647817,0.761297,0.325110,0.094022
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.430000,0.330000,0.500000,0.380000,0.320000,0.430000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.500000,0.330000,0.500000,0.470000,...,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,27.000000,14.000000,11.000000,18.000000,6.000000,1.000000

In [44]:
# Percentage of missing values
missing_percent = (df.isnull().sum() / len(df)) * 100

print(missing_percent.sort_values(ascending=False))

F2911    99.988989
F186     99.988989
F181     99.988989
F2603    99.988989
F2600    99.988989
           ...
F3849     0.000000
F3859     0.000000
F3860     0.000000
F3861     0.000000
F3924     0.000000
Length: 3861, dtype: float64

In [45]:
threshold = 0.99 * len(df)

cols_to_drop = df.columns[df.isnull().sum() > threshold]
df.drop(columns=cols_to_drop, inplace=True)

In [46]:
print(cols_to_drop)

Index(['F36', 'F39', 'F42', 'F45', 'F48', 'F51', 'F134', 'F137', 'F140',
       'F143',
       ...
       'F3122', 'F3125', 'F3127', 'F3128', 'F3129', 'F3130', 'F3287', 'F3290',
       'F3611', 'F3614'],
      dtype='str', length=144)

In [47]:
print(df["F3924"].unique())

[0 1]

In [48]:
df["F3924"].isnull().sum()

np.int64(0)

In [49]:
# Separate features and target
X = df.drop(columns=["F3924"])
y = df["F3924"]

In [50]:
print(X.select_dtypes(exclude=["number"]).columns)

Index(['F2230', 'F3886', 'F3888', 'F3889', 'F3890', 'F3891', 'F3892', 'F3893'], dtype='str')

In [51]:
X[['F2230', 'F3886', 'F3888', 'F3889', 'F3890', 'F3891', 'F3892', 'F3893']].head(10)

   F2230    F3886      F3888  F3889 F3890         F3891 F3892   F3893
0  Oct25  Savings   8-1-2011  G365D     R  selfemployed     M  RETAIL
1  Oct25  Savings   8-2-2011  G365D     R  selfemployed     M  RETAIL
2  Oct25  Savings   8-4-2011  G365D     R       student     M  RETAIL
3  Oct25  Savings   8-4-2011  G365D    SU  selfemployed     M  RETAIL
4  Oct25  Savings   8-8-2011  G365D    SU       student     M  RETAIL
5  Oct25  Current  8-10-2011  G365D    SU  selfemployed     M  RETAIL
6  Oct25  Savings  8-11-2011  G365D     R  selfemployed     M  RETAIL
7  Oct25  Savings  8-16-2011  G365D     M  selfemployed     M  RETAIL
8  Oct25  Savings  8-17-2011  G365D    SU      salaried     M  RETAIL
9  Oct25  Savings  8-19-2011  G365D    SU       student     M  RETAIL

In [52]:
for col in ['F2230', 'F3886', 'F3888', 'F3889', 'F3890', 'F3891', 'F3892', 'F3893']:
    print(f"\n{col}")
    print(X[col].unique())

F2230
<StringArray>
['Oct25', 'Sep25', 'Nov25', 'Dec25']
Length: 4, dtype: str

F3886
<StringArray>
[      'Savings',       'Current',    'MSME Micro',   'MSME Medium',
      'Corp Adv',    'MSME Small',      'Agri Adv', 'Retail LA TDR',
   'Staff Loans',            'ML',            'HL', 'Retail Others',
            'PL',    'All Others',   'MSME LA TDR',     'Gold Loan',
  'Term Deposit']
Length: 17, dtype: str

F3888
<StringArray>
[  '8-1-2011',   '8-2-2011',   '8-4-2011',   '8-8-2011',  '8-10-2011',
  '8-11-2011',  '8-16-2011',  '8-17-2011',  '8-19-2011',  '8-20-2011',
 ...
  '2-16-2018',   '7-3-2014',  '8-16-2004',   '1-5-1988',  '7-27-2005',
  '3-19-2009',  '9-20-1989', '10-28-2011',   '4-4-2017',  '9-24-2007']
Length: 4292, dtype: str

F3889
<StringArray>
['G365D', 'L365D', 'L180D', 'L90D', 'L31D', 'L14D', 'L7D']
Length: 7, dtype: str

F3890
<StringArray>
['R', 'SU', 'M', 'U']
Length: 4, dtype: str

F3891
<StringArray>
['selfemployed',      'student',     'salaried',  'agriculture',
    'housewife',      'retired',       'others']
Length: 7, dtype: str

F3892
<StringArray>
['M', 'F', nan, 'O']
Length: 4, dtype: str

F3893
<StringArray>
['RETAIL', 'CORPORATE']
Length: 2, dtype: str

In [53]:
for col in ['F2230', 'F3886', 'F3888', 'F3889', 'F3890', 'F3891', 'F3892', 'F3893']:
    print(f"\n{col}")
    print(X[col].value_counts(dropna=False))

F2230
F2230
Oct25    9001
Sep25      48
Nov25      23
Dec25      10
Name: count, dtype: int64

F3886
F3886
Savings          5956
Current          2051
MSME Micro        337
MSME Small        242
Staff Loans       108
Agri Adv           96
Term Deposit       87
MSME Medium        71
Corp Adv           23
Gold Loan          23
Retail Others      22
MSME LA TDR        20
Retail LA TDR      19
HL                 10
All Others         10
ML                  4
PL                  3
Name: count, dtype: int64

F3888
F3888
9-19-2025     24
9-17-2025     20
10-13-2025    18
9-23-2025     16
11-7-2025     16
              ..
3-19-2009      1
9-20-1989      1
10-28-2011     1
4-4-2017       1
9-24-2007      1
Name: count, Length: 4292, dtype: int64

F3889
F3889
G365D    7544
L365D     397
L7D       386
L180D     313
L90D      207
L31D      148
L14D       87
Name: count, dtype: int64

F3890
F3890
M     2900
SU    2390
R     2015
U     1777
Name: count, dtype: int64

F3891
F3891
selfemployed    3951
salaried        1909
student         1185
agriculture     1112
housewife        660
others           169
retired           96
Name: count, dtype: int64

F3892
F3892
M      5007
NaN    2598
F      1416
O        61
Name: count, dtype: int64

F3893
F3893
RETAIL       6437
CORPORATE    2645
Name: count, dtype: int64

In [54]:
X[['F2230', 'F3886', 'F3888', 'F3889', 'F3890', 'F3891', 'F3892', 'F3893']].isnull().sum()

F2230       0
F3886       0
F3888       0
F3889       0
F3890       0
F3891       0
F3892    2598
F3893       0
dtype: int64

In [55]:
X["F3892"] = X["F3892"].fillna("Unknown")

In [56]:
from sklearn.impute import SimpleImputer

# Numeric columns
num_cols = X.select_dtypes(include=["number"]).columns


# Median for numeric
num_imputer = SimpleImputer(strategy="median")
X[num_cols] = num_imputer.fit_transform(X[num_cols])

In [58]:
original_columns = df.drop(columns=["F3924"]).columns.tolist()

In [59]:
import joblib


joblib.dump(original_columns, "raw_input_columns.pkl")
joblib.dump(num_imputer, "imputer.pkl")

['imputer.pkl']

In [ ]:
X["F3924"] = y

X.to_csv("Banking_Cleaned.csv", index=False)

PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  X["F3924"] = y